<?php
require_once __DIR__ . '/../classes/arrayClientes.php';
$orderBy = isset($_GET['orderBy'])?($_GET['orderBy']):('asc');
if($orderBy == 'desc') {
    krsort($clientes);
} else {
    ksort($clientes);
}
?>

<h3 class="text-center">Lista de Clientes</h3>
<p>
    <span class="text-info">Listar de forma:</span>
    <a href="/home?orderBy=asc" class="btn btn-link">Ascendente</a>
    |
    <a href="/home?orderBy=desc" class="btn btn-link">Descendente</a>
</p>

<table class="table tab-pane">
    <th>ID</th>
    <th>Nome</th>    
    <th>Ação</th>
<?php foreach($clientes as $cliente):?>
    <tr>
        <td class="col-lg-1"><?=$cliente->getId()?></td>
        <td class="col-lg-1"><?=$cliente->getNome()?></td>
        <td><a href="/cliente?id=<?=$cliente->getId()?>">Visualizar</a></td>
    </tr>
<?php endforeach;?>
</table>